curl https://www.montag.wtf/are-you-really-alive/ -o ~/Desktop/montagarticles/1.html
curl https://www.montag.wtf/irl-2-0-vr-ar-and-reality/ -o ~/Desktop/montagarticles/2.html
curl https://www.montag.wtf/better-than-life-why-leave-a-perfect-alternative-reality/ -o ~/Desktop/montagarticles/3.html
curl https://www.montag.wtf/virtual-ghost-bodies/ -o ~/Desktop/montagarticles/4.html
curl https://www.montag.wtf/a-beautiful-day-in-our-constantly-connected-world/ -o ~/Desktop/montagarticles/5.html
curl https://www.montag.wtf/more-pal-than-hal-the-internet-of-friends-2/ -o ~/Desktop/montagarticles/6.html
curl https://www.montag.wtf/video-games-art/ -o ~/Desktop/montagarticles/7.html
curl https://www.montag.wtf/the-montage-podcast-episode-4/ -o ~/Desktop/montagarticles/8.html
curl https://www.montag.wtf/v-art-vr-doesnt-change-what-art-is-but-it-does-change-how-close-we-get-to-it/ -o ~/Desktop/montagarticles/9.html
curl https://www.montag.wtf/twitterature/ -o ~/Desktop/montagarticles/10.html
curl https://www.montag.wtf/twitter-bot-art/ -o ~/Desktop/montagarticles/11.html
curl https://www.montag.wtf/rewind-the-future-of-music-recommendation-might-not-be-algorithmic-after-all/ -o ~/Desktop/montagarticles/12.html
curl https://www.montag.wtf/2019-predictions-part-2/ -o ~/Desktop/montagarticles/13.html
curl https://www.montag.wtf/2019-predictions/ -o ~/Desktop/montagarticles/14.html
curl https://www.montag.wtf/no-device-can-bring-happiness-its-already-inside-us/ -o ~/Desktop/montagarticles/15.html
curl https://www.montag.wtf/the-montag-christmas-gift-guide/ -o ~/Desktop/montagarticles/16.html
curl https://www.montag.wtf/xmas-excess-the-terrible-happiness-of-made-for-tv-christmas-movies/ -o ~/Desktop/montagarticles/17.html
curl https://www.montag.wtf/what-is-happiness/ -o ~/Desktop/montagarticles/18.html
curl https://www.montag.wtf/the-montage-podcast-episode-15-who-said-it-dril/ -o ~/Desktop/montagarticles/19.html
curl https://www.montag.wtf/ai-happiness/ -o ~/Desktop/montagarticles/20.html
curl https://www.montag.wtf/reject-ambition-work-less-happiness-in-washing-machines/ -o ~/Desktop/montagarticles/21.html
curl https://www.montag.wtf/smiley-face/ -o ~/Desktop/montagarticles/22.html
curl https://www.montag.wtf/gross-national-happiness/ -o ~/Desktop/montagarticles/23.html
curl https://www.montag.wtf/the-montage-podcast-episode-14-a-2019-weird-predictions-special/ -o ~/Desktop/montagarticles/24.html
curl https://www.montag.wtf/free-money-expensive-time-how-will-we-use-cash-tomorrow/ -o ~/Desktop/montagarticles/25.html
curl https://www.montag.wtf/far-from-the-nomadding-crowd/ -o ~/Desktop/montagarticles/26.html
curl https://www.montag.wtf/microtransactions-and-your-soul/ -o ~/Desktop/montagarticles/27.html
curl https://www.montag.wtf/adventures-in-altcoin/ -o ~/Desktop/montagarticles/28.html
curl https://www.montag.wtf/everything-someone-who-knows-nothing-about-cryptocurrency-needs-to-know-about-cryptocurrency-by-someone-who-knows-nothing-about-cryptocurrency/ -o ~/Desktop/montagarticles/29.html
curl https://www.montag.wtf/billionaires-going-to-space/ -o ~/Desktop/montagarticles/30.html
curl https://www.montag.wtf/party-on-the-dark-web/ -o ~/Desktop/montagarticles/31.html
curl https://www.montag.wtf/a-superstar-forever/ -o ~/Desktop/montagarticles/32.html
curl https://www.montag.wtf/back-to-the-drawing-board-try-vr-painting-and-change-how-you-see-the-world/ -o ~/Desktop/montagarticles/33.html
curl https://www.montag.wtf/montag-fiction-npc-quest/ -o ~/Desktop/montagarticles/34.html
curl https://www.montag.wtf/inside-an-avatar-we-are-cyborgs/ -o ~/Desktop/montagarticles/35.html
curl https://www.montag.wtf/dystopia-the-handmaids-tale/ -o ~/Desktop/montagarticles/36.html
curl https://www.montag.wtf/sound-affects-music-might-be-your-new-medicine/ -o ~/Desktop/montagarticles/37.html
curl https://www.montag.wtf/bot-love/ -o ~/Desktop/montagarticles/38.html
curl https://www.montag.wtf/credit-where-its-due-will-technology-make-the-poor-artist-a-thing-of-the-past/ -o ~/Desktop/montagarticles/39.html
curl https://www.montag.wtf/do-it-yourself-post-entertainment-for-the-individual-and-the-personalised-narrative/ -o ~/Desktop/montagarticles/40.html
curl https://www.montag.wtf/doing-the-robot/ -o ~/Desktop/montagarticles/41.html
curl https://www.montag.wtf/neural-network-nightmare-fuel/ -o ~/Desktop/montagarticles/42.html
curl https://www.montag.wtf/computers-have-learnt-to-play-computer-games-and-theyre-better-than-youll-ever-be/ -o ~/Desktop/montagarticles/43.html
curl https://www.montag.wtf/everything-has-been-photographed/ -o ~/Desktop/montagarticles/44.html
curl https://www.montag.wtf/beer-in-space/ -o ~/Desktop/montagarticles/45.html
curl https://www.montag.wtf/escape-rooms/ -o ~/Desktop/montagarticles/46.html
curl https://www.montag.wtf/todays-dystopia-idiocracy/ -o ~/Desktop/montagarticles/47.html
curl https://www.montag.wtf/its-not-who-you-know-its-what-you-know-the-next-generation-of-job-recruiters-dont-care-who-you-are-because-theyre-robots/ -o ~/Desktop/montagarticles/48.html
curl https://www.montag.wtf/todays-dystopia-blade-runner/ -o ~/Desktop/montagarticles/49.html
curl https://www.montag.wtf/boost-your-brain/ -o ~/Desktop/montagarticles/50.html
curl https://www.montag.wtf/consume-young-blood-live-longer-embrace-your-inner-vampire/ -o ~/Desktop/montagarticles/51.html
curl https://www.montag.wtf/future-funereals/ -o ~/Desktop/montagarticles/52.html
curl https://www.montag.wtf/eliminate-mosquitoes-smart-thinking/ -o ~/Desktop/montagarticles/53.html
curl https://www.montag.wtf/i-want-a-new-drug/ -o ~/Desktop/montagarticles/54.html
curl https://www.montag.wtf/who-is-douglas-dollars/ -o ~/Desktop/montagarticles/55.html
curl https://www.montag.wtf/buy-a-share-of-mike/ -o ~/Desktop/montagarticles/56.html
curl https://www.montag.wtf/coinz-4-clickz/ -o ~/Desktop/montagarticles/57.html
curl https://www.montag.wtf/the-montage-podcast-episode-7-sell-body-parts-make-money/ -o ~/Desktop/montagarticles/58.html
curl https://www.montag.wtf/do-we-want-cash-to-disappear/ -o ~/Desktop/montagarticles/59.html
curl https://www.montag.wtf/alternative-economies-and-how-capitalism-ruins-them/ -o ~/Desktop/montagarticles/60.html
curl https://www.montag.wtf/thats-not-what-i-meant-incomplete-data-f-cks-up-conversations/ -o ~/Desktop/montagarticles/61.html
curl https://www.montag.wtf/todays-dystopia-fahrenheit-451/ -o ~/Desktop/montagarticles/62.html
curl https://www.montag.wtf/todays-dystopia-the-city-the-stars/ -o ~/Desktop/montagarticles/63.html
curl https://www.montag.wtf/travelling-without-moving-tripping-through-time-in-vr/ -o ~/Desktop/montagarticles/64.html
curl https://www.montag.wtf/deep-dream/ -o ~/Desktop/montagarticles/65.html
curl https://www.montag.wtf/momento-mori-dead-relative-vr/ -o ~/Desktop/montagarticles/66.html
curl https://www.montag.wtf/lab-grown-burgers/ -o ~/Desktop/montagarticles/67.html
curl https://www.montag.wtf/montag-fiction-ransomwear/ -o ~/Desktop/montagarticles/68.html
curl https://www.montag.wtf/history-meaning-of-emoji-language/ -o ~/Desktop/montagarticles/69.html
curl https://www.montag.wtf/thats-not-what-i-meant-part-2/ -o ~/Desktop/montagarticles/70.html
curl https://www.montag.wtf/anti-tech-technology-part-2-the-man-who-disappeared-completely/ -o ~/Desktop/montagarticles/71.html
curl https://www.montag.wtf/how-to-disappear/ -o ~/Desktop/montagarticles/72.html
curl https://www.montag.wtf/gaming-the-system-your-life-has-become-the-biggest-game-youve-n-ever-played/ -o ~/Desktop/montagarticles/73.html
curl https://www.montag.wtf/burger-flippin-coffee-drippin/ -o ~/Desktop/montagarticles/74.html
curl https://www.montag.wtf/todays-dystopia-fun-and-games-of-fiction/ -o ~/Desktop/montagarticles/75.html
curl https://www.montag.wtf/lets-talk-about-ready-player-one/ -o ~/Desktop/montagarticles/76.html
curl https://www.montag.wtf/the-montage-podcast-episode-8-how-to-become-a-cyborg-right-now-and-how-robots-will-steal-your-creative-job/ -o ~/Desktop/montagarticles/77.html
curl https://www.montag.wtf/break-the-world/ -o ~/Desktop/montagarticles/78.html
curl https://www.montag.wtf/the-entrenched-connection-you-already-create-enough-data-to-make-you-happier-but-do-you-want-to-do-it/ -o ~/Desktop/montagarticles/79.html
curl https://www.montag.wtf/frozen-cryonics-cryogenics-reanimation-and-walt-disney/ -o ~/Desktop/montagarticles/80.html
curl https://www.montag.wtf/montag-fiction-formatting-error/ -o ~/Desktop/montagarticles/81.html
curl https://www.montag.wtf/all-in-the-mind-mind-control-is-here-but-not-in-the-way-you-really-want/ -o ~/Desktop/montagarticles/82.html
curl https://www.montag.wtf/the-power-of-music-and-soft-brain-hacking/ -o ~/Desktop/montagarticles/83.html
curl https://www.montag.wtf/lovely-weather-were-having/ -o ~/Desktop/montagarticles/84.html
curl https://www.montag.wtf/the-montage-podcast-episode-13/ -o ~/Desktop/montagarticles/85.html
curl https://www.montag.wtf/primal-screen-your-screen-is-not-making-you-happy/ -o ~/Desktop/montagarticles/86.html
curl https://www.montag.wtf/minimalism-to-be-happy/ -o ~/Desktop/montagarticles/87.html
curl https://www.montag.wtf/hacking-happiness/ -o ~/Desktop/montagarticles/88.html
curl https://www.montag.wtf/the-montage-podcast-episode-12/ -o ~/Desktop/montagarticles/89.html
curl https://www.montag.wtf/harder-better-athletes-technology/ -o ~/Desktop/montagarticles/90.html
curl https://www.montag.wtf/komfort-future-technologies/ -o ~/Desktop/montagarticles/91.html
curl https://www.montag.wtf/new-musical-excess-why-musicians-are-ignoring-the-newest-instruments-and-what-theyll-play-next/ -o ~/Desktop/montagarticles/92.html
curl https://www.montag.wtf/the-montage-podcast-3/ -o ~/Desktop/montagarticles/93.html
curl https://www.montag.wtf/imitate-talent-steal-geniuses-when-technology-copies-art/ -o ~/Desktop/montagarticles/94.html
curl https://www.montag.wtf/fiction-011/ -o ~/Desktop/montagarticles/95.html
curl https://www.montag.wtf/todays-dystopia-equilibrium/ -o ~/Desktop/montagarticles/96.html
curl https://www.montag.wtf/do-you-think-this-is-a-game/ -o ~/Desktop/montagarticles/97.html
curl https://www.montag.wtf/the-montage-podcast-episode-10-the-benefits-of-other-peoples-blood-and-adventures-in-asmr/ -o ~/Desktop/montagarticles/98.html
curl https://www.montag.wtf/behold-verisimulators-videogames-that-exactly-replicate-the-mudanity-of-real-life-and-theyre-the-future-of-work-and-play/ -o ~/Desktop/montagarticles/99.html
curl https://www.montag.wtf/fully-automated-luxury-gay-space-communism/ -o ~/Desktop/montagarticles/100.html
curl https://www.montag.wtf/the-montage-podcast-episode-9-have-your-remains-turned-into-a-diamond-and-fired-into-space-plus-antique-burps/ -o ~/Desktop/montagarticles/101.html
curl https://www.montag.wtf/satellite-of-love-17776-football/ -o ~/Desktop/montagarticles/102.html
curl https://www.montag.wtf/set-phasers-to-glam/ -o ~/Desktop/montagarticles/103.html
curl https://www.montag.wtf/automatic-for-the-people-part-1/ -o ~/Desktop/montagarticles/104.html
curl https://www.montag.wtf/and-action-your-life-is-about-to-become-a-story-written-by-you/ -o ~/Desktop/montagarticles/105.html
curl https://www.montag.wtf/sunspring-sci-fi-by-ai/ -o ~/Desktop/montagarticles/106.html
curl https://www.montag.wtf/the-montage-podcast-episode-1-sextech-soylent-ufos/ -o ~/Desktop/montagarticles/107.html
curl https://www.montag.wtf/todays-dystopia-a-scanner-darkly/ -o ~/Desktop/montagarticles/108.html
curl https://www.montag.wtf/biohacking-drugs-gut-flora/ -o ~/Desktop/montagarticles/109.html
curl https://www.montag.wtf/todays-dystopia-johnny-mnemonic/ -o ~/Desktop/montagarticles/110.html
curl https://www.montag.wtf/ray-against-the-machine-transhumanisms-savant-prince-has-called-time-on-humanity/ -o ~/Desktop/montagarticles/111.html
curl https://www.montag.wtf/sell-yourself-your-data/ -o ~/Desktop/montagarticles/112.html
curl https://www.montag.wtf/the-quantified-self-biohacking-guerrilla-data-and-our-self-health-future/ -o ~/Desktop/montagarticles/113.html
curl https://www.montag.wtf/human-augmentation/ -o ~/Desktop/montagarticles/114.html
curl https://www.montag.wtf/this-didnt-write-itself-ai-is-coming-for-your-creative-jobs-too/ -o ~/Desktop/montagarticles/115.html
curl https://www.montag.wtf/flesh-wearables/ -o ~/Desktop/montagarticles/116.html
curl https://www.montag.wtf/wtf-how-future-humans-will-look-back-on-todays-healthcare-with-horror-and-amazement/ -o ~/Desktop/montagarticles/117.html
curl https://www.montag.wtf/untitled/ -o ~/Desktop/montagarticles/118.html
curl https://www.montag.wtf/organ-cloner-grow-body-parts/ -o ~/Desktop/montagarticles/119.html
curl https://www.montag.wtf/sell-yourself-part-2-your-body/ -o ~/Desktop/montagarticles/120.html
curl https://www.montag.wtf/artificial-intelligence-you-i-i-i-i-i-everything-else/ -o ~/Desktop/montagarticles/121.html
curl https://www.montag.wtf/the-montage-podcast-episode-2/ -o ~/Desktop/montagarticles/122.html
curl https://www.montag.wtf/fun-with-neural-networks/ -o ~/Desktop/montagarticles/123.html
curl https://www.montag.wtf/todays-dystopia-they-live/ -o ~/Desktop/montagarticles/124.html
curl https://www.montag.wtf/coding-creativity/ -o ~/Desktop/montagarticles/125.html
curl https://www.montag.wtf/automatic-for-the-people-part-two/ -o ~/Desktop/montagarticles/126.html
curl https://www.montag.wtf/the-montage-podcast-episode-11-are-ai-written-movies-and-music-any-good-plus-kathryn-reigns-as-kwiz-kween-once-more/ -o ~/Desktop/montagarticles/127.html
curl https://www.montag.wtf/future-workwear/ -o ~/Desktop/montagarticles/128.html
curl https://www.montag.wtf/is-there-life-in-the-old-dog-yet-or-are-robo-pets-ready-to-replace-our-furry-friends/ -o ~/Desktop/montagarticles/129.html
curl https://www.montag.wtf/turkin-for-the-weekend/ -o ~/Desktop/montagarticles/130.html
curl https://www.montag.wtf/montag-fiction-15-ruya-saw-it-all/ -o ~/Desktop/montagarticles/131.html
curl https://www.montag.wtf/alternate-reality-games/ -o ~/Desktop/montagarticles/132.html
curl https://www.montag.wtf/i-was-there/ -o ~/Desktop/montagarticles/133.html
curl https://www.montag.wtf/sextech-futuresex-could-you-resist-your-perfect-fantasy/ -o ~/Desktop/montagarticles/134.html
curl https://www.montag.wtf/welcome-to-montag-where-every-day-is-tomorrow/ -o ~/Desktop/montagarticles/135.html
curl https://www.montag.wtf/can-you-be-too-happy-and-other-ridiculous-questions-posed-by-humans-in-the-search-of-true-happiness/ -o ~/Desktop/montagarticles/136.html
curl https://www.montag.wtf/emotional-surveillance/ -o ~/Desktop/montagarticles/137.html
curl https://www.montag.wtf/comed-ai-a-neural-network-a-twitter-bot-and-an-artificial-intelligence/ -o ~/Desktop/montagarticles/138.html
curl https://www.montag.wtf/hell-is-other-people-except-actually-its-not-at-all/ -o ~/Desktop/montagarticles/139.html
curl https://www.montag.wtf/happiness-dot-com/ -o ~/Desktop/montagarticles/140.html
curl https://www.montag.wtf/montag-investigates-an-entirely-un-scientific-and-non-thorough-investigation-of-happiness-on-youtube/ -o ~/Desktop/montagarticles/141.html
curl https://www.montag.wtf/montag-fiction-014-btc-to-the-future/ -o ~/Desktop/montagarticles/142.html
curl https://www.montag.wtf/post-apocalyptic-cash/ -o ~/Desktop/montagarticles/143.html
curl https://www.montag.wtf/if-money-is-all-in-the-mind-could-we-just-ignore-it/ -o ~/Desktop/montagarticles/144.html
curl https://www.montag.wtf/episode-5-talking-in-emoji-and-arthur-c-clarkes-the-city-and-the-stars/ -o ~/Desktop/montagarticles/145.html
curl https://www.montag.wtf/when-bots-become-us-will-we-become-bots/ -o ~/Desktop/montagarticles/146.html
curl https://www.montag.wtf/online-shopping-under-the-influence/ -o ~/Desktop/montagarticles/147.html
curl https://www.montag.wtf/how-much-would-you-pay-to-meet-your-soulmate/ -o ~/Desktop/montagarticles/148.html
curl https://www.montag.wtf/is-happiness-a-vat/ -o ~/Desktop/montagarticles/149.html
curl https://www.montag.wtf/the-montage-podcast-6-eating-panda-meat-and-selling-your-data/ -o ~/Desktop/montagarticles/150.html
curl https://www.montag.wtf/girls-gone-crypto/ -o ~/Desktop/montagarticles/151.html
curl https://www.montag.wtf/what-if-we-stopped-buying-things/ -o ~/Desktop/montagarticles/152.html
curl https://www.montag.wtf/todays-dystopia-credit-where-its-due-currencies-in-sci-fi/ -o ~/Desktop/montagarticles/153.html
curl https://www.montag.wtf/high-low-tech-sms-tractors-and-leds-are-the-real-cutting-edge/ -o ~/Desktop/montagarticles/154.html
curl https://www.montag.wtf/a-drone-will-save-your-life-probably/ -o ~/Desktop/montagarticles/155.html
curl https://www.montag.wtf/vr-the-victorian-revolution/ -o ~/Desktop/montagarticles/156.html
curl https://www.montag.wtf/soylent-dinner-for-one/ -o ~/Desktop/montagarticles/157.html
curl https://www.montag.wtf/my-toaster-wont-stop-calling-you/ -o ~/Desktop/montagarticles/158.html
curl https://www.montag.wtf/digital-idols-hatsune-miku-vr-concert/ -o ~/Desktop/montagarticles/159.html
